apiVersion: v1
kind: Namespace
metadata:
  name: ecom

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom
  labels:
    app: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom
  template:
    metadata:
      labels:
        app: ecom
    spec:
      containers:
      - name: ecom
        image: REPOSITORY_TAG

---

apiVersion: v1
kind: Service
metadata:
  name: ecom-svc
spec:
  selector:
    app: ecom
  ports:
    - name: http
      port: 3000

  type: ClusterIP
